### ISSUE TITLE
Error valid value range is empty

### ISSUE THREAD

**Issue by hortigado** [bikram0000/getx_translator#1]
flutter pub run getx_translator:main
💡 [GETX_TRANSLATOR] creating.. Output Directory assets/translation
💡 [GETX_TRANSLATOR] Getting keys from sheet..
Unhandled exception:
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      List.removeAt (dart:core-patch/growable_array.dart:23:22)
#2      GetxTranslator.getOldKey (package:getx_translator/getx_translator.dart:331:17)
<asynchronous suspension>
#3      GetxTranslator.exec (package:getx_translator/getx_translator.dart:59:7)
<asynchronous suspension>
![image](https://user-images.githubusercontent.com/42924254/215392364-04298635-0518-4abc-b70b-3139278da585.png)

**Comment by hortigado** [comment]
I clone the example excel  and work
