### ISSUE TITLE
Unhandled exception: FormatException: Unexpected character (at character 1)

### ISSUE THREAD

**Issue by santhosh-D-subramani** [bikram0000/getx_translator#7]
what i did : 
- copied example google sheet and update my sheet_url, sheet_id in pubspec.yaml

```
PS \untitled1getxtranslatetest>   flutter pub run getx_translator:main
Deprecated. Use `dart run` instead.
💡 [GETX_TRANSLATOR] creating.. Output Directory assets/language
💡 [GETX_TRANSLATOR] Getting keys from sheet..
Unhandled exception:
FormatException: Unexpected character (at character 1)
<!DOCTYPE html><html><head><link rel="shortcut icon" href="//ssl.gstatic.co...
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1332:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:933:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
#4      JsonDecoder.convert (dart:convert/json.dart:610:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      jsonDecode (dart:convert/json.dart:155:10)
#7      GetxTranslator.getSheetData (package:getx_translator/getx_translator.dart:525:15)       
<asynchronous suspension>
#8      GetxTranslator.getOldKey (package:getx_translator/getx_translator.dart:328:23)
<asynchronous suspension>
#9      GetxTranslator.exec (package:getx_translator/getx_translator.dart:59:7)
<asynchronous suspension>
```

**Comment by bikram0000** [comment]
Kindly use latest from git url

**Comment by santhosh-D-subramani** [comment]
I just cloned the repo , still getting same error
```
PS C:\Users\hfmmb\StudioProjects\getx_translator\example> flutter pub run getx_translator:main
Deprecated. Use `dart run` instead.
Building package executable... 
Built getx_translator:main.
💡 [GETX_TRANSLATOR] creating.. Output Directory assets/language
💡 [GETX_TRANSLATOR] Getting keys from sheet..
Unhandled exception:
FormatException: Unexpected character (at character 1)
<!DOCTYPE html><html lang="en"><head><meta name="description" content="Web ...
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1332:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:933:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
#4      JsonDecoder.convert (dart:convert/json.dart:610:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      jsonDecode (dart:convert/json.dart:155:10)
#7      GetxTranslator.getSheetData (package:getx_translator/getx_translator.dart:536:15)      
<asynchronous suspension>
#8      GetxTranslator.getOldKey (package:getx_translator/getx_translator.dart:330:23)
<asynchronous suspension>
#9      GetxTranslator.exec (package:getx_translator/getx_translator.dart:59:7)
<asynchronous suspension>

```

**Comment by bikram0000** [comment]
Make sure your google sheet is available for others, Its a issue with permission for that sheet.

**Comment by bikram0000** [comment]
I think google change some policy related to sheet apis, I will check it soon and update this

**Comment by santhosh-D-subramani** [comment]
sure 👍

**Comment by bikram0000** [comment]
Hello, I have checked it again while you deploying the script for google sheet. You have to deploy it as a web app and make it for anyone.
<img width="540" alt="Screenshot 2024-10-23 at 9 19 34 PM" src="https://github.com/user-attachments/assets/53327148-c618-4ce1-b333-b23d3e0281f1">


For demo you can now use 

`getx_translator:
  path: "lib"
  output_path: "assets/language"
  sheet_url: "https://script.google.com/macros/s/AKfycbxZH6QVwiGXwkdLWx9_NZJx8pjHDUtBmRBZBLPX_hj172SHLXG2ppbB6-DpLlZMVldxqw/exec"
  sheet_name: "Sheet1"
  sheet_id: "1G1e_LLT9kRXVjnHApMdp4LLwvBxvr-Z1orn0U7VxQF8"`

**Comment by santhosh-D-subramani** [comment]
I got it, 
I was putting wrong  sheet_id , now it's working.
demo didn't work for me though, I copied the sheet
